### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by joshday**
This is combination of cleanup and separating concerns.

Most folks on the JuliaHub side will be able to stay inside operations.jl.

Thanks to @fivegrant's recent additions to https://github.com/DARPA-ASKEM/simulation-api-spec/blob/main/flows/simulate/README.md, I think I have all the requests to the TDS/HMI fixed.

### CODE REVIEW

**Review by fivegrant — CHANGES_REQUESTED** [review]
Looks like on model creation, that PUT is used instead of a POST. I think the payload may need to be reshaped: 
```
{"detail":[{"loc":["body","id"],"msg":"field required","type":"value_error.missing"},{"loc":["body","engine"],"msg":"field required","type":"value_error.missing"},{"loc":["body","type"],"msg":"field required","type":"value_error.missing"},{"loc":["body","execution_payload"],"msg":"field required","type":"value_error.missing"},{"loc":["body","workflow_id"],"msg":"field required","type":"value_error.missing"}]}""")
```

Also, the docker build could probably be fixed: https://github.com/DARPA-ASKEM/simulation-service/issues/71

**Comment by joshday** [comment]
Model creation does use POST: 

- `create` definition:

https://github.com/DARPA-ASKEM/simulation-service/blob/5cce7ca7a1e4405e121c83b9526c32fb17d14a44/src/SimulationService.jl#L334-L338

- Where it's used in POST /{operation}

https://github.com/DARPA-ASKEM/simulation-service/blob/5cce7ca7a1e4405e121c83b9526c32fb17d14a44/src/SimulationService.jl#L394-L400

**Comment by joshday** [comment]
What is the payload you're referring to?

**Comment by joshday** [comment]
> What is the payload you're referring to?

Never mind, those are the errors.  Got it.

**Comment by joshday** [comment]
Hmm, this is what `create` is POST-ing.

```json
{"id":"sciml-58a0da15-5d2f-4c92-a4e0-0db9ed523164","engine":"sciml","type":"simulate","execution_payload":{"local_model_file":"/Users/joshday/github/simulation-service/test/../examples/BIOMD0000000955_askenet.json","timespan":{"start":0,"end":100}},"workflow_id":"IGNORED","timestamp":"2023-07-14T14:00:25.517","result_files":null,"status":"queued","reason":null,"start_time":null,"completed_time":null,"user_id":null,"project_id":null}
```

**Comment by fivegrant** [comment]
TDS:
```
data-service-api         | INFO:     192.168.144.1:53464 - "GET /model_configurations/d9b8d9e4-6815-406a-9d0b-ff25fdec13a9 HTTP/1.1" 200 OK
data-service-api         | INFO:     192.168.144.1:58374 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:58400 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:58402 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:58412 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57154 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57160 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57180 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57206 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57214 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57242 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57258 - "PUT /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 422 Unprocessable Entity
data-service-api         | INFO:     192.168.144.1:57274 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57294 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:57316 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48308 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48314 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48338 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48352 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48368 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48386 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48420 - "GET /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 404 Not Found
data-service-api         | INFO:     192.168.144.1:48422 - "PUT /simulations/sciml-c75446d7-37c4-4c56-8e3a-1289d8ca9ab9 HTTP/1.1" 422 Unprocessable Entity
```

**Comment by fivegrant** [comment]
```
""
HTTP/1.1 422 Unprocessable Entity
date: Fri, 14 Jul 2023 14:30:29 GMT
server: uvicorn
content-length: 412
content-type: application/json

{"detail":[{"loc":["body","id"],"msg":"field required","type":"value_error.missing"},{"loc":["body","engine"],"msg":"field required","type":"value_error.missing"},{"loc":["body","type"],"msg":"field required","type":"value_error.missing"},{"loc":["body","execution_payload"],"msg":"field required","type":"value_error.missing"},{"loc":["body","workflow_id"],"msg":"field required","type":"value_error.missing"}]}""")
Stacktrace:
  [1] (::HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}})(stream::HTTP.Streams.Stream{HTTP.Messages.Response, HTTP.Connections.Connection{Sockets.TCPSocket}}; status_exception::Bool, timedout::Nothing, logerrors::Bool, logtag::Nothing, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ HTTP.ExceptionRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/ExceptionRequest.jl:19
  [2] exceptions
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/ExceptionRequest.jl:13 [inlined]
  [3] (::HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}})(stream::HTTP.Streams.Stream{HTTP.Messages.Response, HTTP.Connections.Connection{Sockets.TCPSocket}}; readtimeout::Int64, logerrors::Bool, logtag::Nothing, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ HTTP.TimeoutRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/TimeoutRequest.jl:17
  [4] (::HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}})(req::HTTP.Messages.Request; proxy::Nothing, socket_type::Type, socket_type_tls::Type, readtimeout::Int64, connect_timeout::Int64, logerrors::Bool, logtag::Nothing, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ HTTP.ConnectionRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/ConnectionRequest.jl:120
  [5] (::Base.var"#90#92"{Base.var"#90#91#93"{ExponentialBackOff, HTTP.RetryRequest.var"#2#5"{Int64, typeof(HTTP.RetryRequest.FALSE), HTTP.Messages.Request, Base.RefValue{Int64}}, HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}})(args::HTTP.Messages.Request; kwargs::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ Base ./error.jl:296
  [6] (::HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}})(req::HTTP.Messages.Request; retry::Bool, retries::Int64, retry_delays::ExponentialBackOff, retry_check::Function, retry_non_idempotent::Bool, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ HTTP.RetryRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/RetryRequest.jl:75
  [7] manageretries
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/RetryRequest.jl:30 [inlined]
  [8] (::HTTP.CookieRequest.var"#managecookies#4"{HTTP.CookieRequest.var"#managecookies#1#5"{HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}}}})(req::HTTP.Messages.Request; cookies::Bool, cookiejar::HTTP.Cookies.CookieJar, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
    @ HTTP.CookieRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/CookieRequest.jl:42
  [9] managecookies
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/CookieRequest.jl:19 [inlined]
 [10] (::HTTP.HeadersRequest.var"#defaultheaders#2"{HTTP.HeadersRequest.var"#defaultheaders#1#3"{HTTP.CookieRequest.var"#managecookies#4"{HTTP.CookieRequest.var"#managecookies#1#5"{HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}}}}}})(req::HTTP.Messages.Request; iofunction::Nothing, decompress::Nothing, basicauth::Bool, detect_content_type::Bool, canonicalize_headers::Bool, kw::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbose,), Tuple{Int64}}})
    @ HTTP.HeadersRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/HeadersRequest.jl:71
 [11] defaultheaders
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/HeadersRequest.jl:14 [inlined]
 [12] (::HTTP.RedirectRequest.var"#redirects#3"{HTTP.RedirectRequest.var"#redirects#1#4"{HTTP.HeadersRequest.var"#defaultheaders#2"{HTTP.HeadersRequest.var"#defaultheaders#1#3"{HTTP.CookieRequest.var"#managecookies#4"{HTTP.CookieRequest.var"#managecookies#1#5"{HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}}}}}}}})(req::HTTP.Messages.Request; redirect::Bool, redirect_limit::Int64, redirect_method::Nothing, forwardheaders::Bool, response_stream::Nothing, kw::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbose,), Tuple{Int64}}})
    @ HTTP.RedirectRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/RedirectRequest.jl:25
 [13] redirects
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/RedirectRequest.jl:14 [inlined]
 [14] (::HTTP.MessageRequest.var"#makerequest#3"{HTTP.MessageRequest.var"#makerequest#1#4"{HTTP.RedirectRequest.var"#redirects#3"{HTTP.RedirectRequest.var"#redirects#1#4"{HTTP.HeadersRequest.var"#defaultheaders#2"{HTTP.HeadersRequest.var"#defaultheaders#1#3"{HTTP.CookieRequest.var"#managecookies#4"{HTTP.CookieRequest.var"#managecookies#1#5"{HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}}}}}}}}}})(method::String, url::URIs.URI, headers::Vector{Pair{String, String}}, body::String; copyheaders::Bool, response_stream::Nothing, http_version::HTTP.Strings.HTTPVersion, verbose::Int64, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HTTP.MessageRequest ~/.julia/packages/HTTP/7FAFf/src/clientlayers/MessageRequest.jl:35
 [15] makerequest
    @ ~/.julia/packages/HTTP/7FAFf/src/clientlayers/MessageRequest.jl:24 [inlined]
 [16] request(stack::HTTP.MessageRequest.var"#makerequest#3"{HTTP.MessageRequest.var"#makerequest#1#4"{HTTP.RedirectRequest.var"#redirects#3"{HTTP.RedirectRequest.var"#redirects#1#4"{HTTP.HeadersRequest.var"#defaultheaders#2"{HTTP.HeadersRequest.var"#defaultheaders#1#3"{HTTP.CookieRequest.var"#managecookies#4"{HTTP.CookieRequest.var"#managecookies#1#5"{HTTP.RetryRequest.var"#manageretries#3"{HTTP.RetryRequest.var"#manageretries#1#4"{HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}}}}}}}}}}}}, method::String, url::String, h::Vector{Pair{String, String}}, b::String, q::Nothing; headers::Vector{Pair{String, String}}, body::String, query::Nothing, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HTTP ~/.julia/packages/HTTP/7FAFf/src/HTTP.jl:457
 [17] request(stack::Function, method::String, url::String, h::Vector{Pair{String, String}}, b::String, q::Nothing)
    @ HTTP ~/.julia/packages/HTTP/7FAFf/src/HTTP.jl:455
 [18] #request#20
    @ ~/.julia/packages/HTTP/7FAFf/src/HTTP.jl:315 [inlined]
 [19] request
    @ ~/.julia/packages/HTTP/7FAFf/src/HTTP.jl:313 [inlined]
 [20] put(::String, ::Vararg{Any}; kw::Base.Pairs{Symbol, String, Tuple{Symbol}, NamedTuple{(:body,), Tuple{String}}})
    @ HTTP ~/.julia/packages/HTTP/7FAFf/src/HTTP.jl:525
 [21] update_job_status!(o::SimulationService.OperationRequest{SimulationService.Simulate}; kw::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:status, :start_time), Tuple{String, Float64}}})
    @ SimulationService ~/sciml-service/src/SimulationService.jl:388
 [22] update_job_status!
    @ ~/sciml-service/src/SimulationService.jl:379 [inlined]
 [23] solve!(o::SimulationService.OperationRequest{SimulationService.Simulate})
    @ SimulationService ~/sciml-service/src/SimulationService.jl:420
 [24] (::SimulationService.var"#48#49"{SimulationService.OperationRequest{SimulationService.Simulate}})()
    @ SimulationService ./task.jl:134
 [25] (::JobSchedulers.var"#13#15"{Task})()
    @ JobSchedulers ~/.julia/packages/JobSchedulers/5Qozb/src/jobs.jl:105
 [26] try_function(f::JobSchedulers.var"#13#15"{Task}, #unused#::Nothing)
    @ Pipelines ~/.julia/packages/Pipelines/IXsWi/src/redirection.jl:151
 [27] #redirect_to_files#7
    @ ~/.julia/packages/Pipelines/IXsWi/src/redirection.jl:223 [inlined]
 [28] redirect_to_files
    @ ~/.julia/packages/Pipelines/IXsWi/src/redirection.jl:200 [inlined]
 [29] #redirect_to_files#8
    @ ~/.julia/packages/Pipelines/IXsWi/src/redirection.jl:273 [inlined]
 [30] redirect_to_files
    @ ~/.julia/packages/Pipelines/IXsWi/src/redirection.jl:273 [inlined]
 [31] (::JobSchedulers.var"#12#14"{Nothing, Nothing, Bool, Task})()
    @ JobSchedulers ./task.jl:134
```

**Comment by joshday** [comment]
@fivegrant the above errors are from an old commit (they mention a function that doesn't exist anymore).

**Comment by joshday** [comment]
@fivegrant I've tested this with the TDS enabled (see the `test/tds.jl` file) and all looks good.

**Review by fivegrant — APPROVED** [review]
Let's try to see if this works with the HMI!

**Comment by joshday** [comment]
@fivegrant currently I've only tested /simulate.

There's an error with /calibrate, but I believe Chris has fixed it with his PR.  I'm waiting for CI results before merging his branch into here

**Pull request merged**
