### PR TITLE
Jd/dockerfile2

### PR DESCRIPTION
**Pull request by joshday**
Trying to fix the docker build.

@fivegrant to clarify on what these files are: 

1) `Project.toml` declares dependencies.
2) `Manifest.toml` gives you the exact versions that are currently installed.  It's typically not checked into a git repo.

If we want dependencies fixed/pinned to specific versions, I'd argue this should be done via the `Project.toml` file's `[compat]` section.  The CI will run on the latest available versions, so as long as we wait for the checks to run we know the tests complete successfully on the latest available package versions.

Also I don't think the `Pkg.resolve()` is doing anything that the `Pkg.instantiate()` didn't already do.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should we have a manifest in here?

**Comment by joshday** [comment]
@ChrisRackauckas Maybe.  Depends on how bleeding-edge we need to be.

**Comment by joshday** [comment]
Okay yeah, I think we do want a Manifest.  I `Pkg.update`-ed in the last few days, but if there's any brand new things that occurred since then I've missed it.

**Comment by ChrisRackauckas** [comment]
I can handle manifest bumps, since anything we'd want would come from SciML. But I think with the hackathon done we're good to lock it down.

**Review by fivegrant — APPROVED** [review]
Still builds on my machine. It's probably worth letting someone handling deployments know (@chris-dickson, @YohannParis, or @dgauldie) when you merge the main and begin building the image

**Comment by joshday** [comment]
@fivegrant @chris-dickson @YohannParis @dgauldie

Sorry for pinging all of you!  I'm not sure who I should be asking:

Does merging to main automatically kick off a deployment?  I'm unsure of what the `publish.yaml` GH action does.

**Pull request merged**
